name: Run QA Check with Playwright

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape-and-log:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install

      - name: 💻 Run QA script by 21f3002753@ds.study.iitm.ac.in
        run: node scraper.js
